import { useState } from "react";
import styled from "styled-components";
import aiDocument from "../../assets/icons/folder/ai-document.svg";
import checkIcon from "../../assets/icons/folder/check.svg";

const Panel=styled.aside`position:sticky;top:24px;width:312px;height:663px;border:1px solid ${({theme})=>theme.colors.border};border-radius:12px;background:white;overflow:hidden;@media(max-width:980px){position:static;width:100%;}`;
const Header=styled.h2`padding:18px 16px;border-bottom:1px solid ${({theme})=>theme.colors.border};font-size:13px;line-height:20px;`;
const Body=styled.div`padding:14px 16px;`;
const StepHead=styled.div`display:flex;align-items:center;justify-content:space-between;padding:8px 0 12px;font-size:12px;font-weight:700;img{width:24px;height:24px;}span{display:flex;align-items:center;gap:8px;}em{color:${({theme})=>theme.colors.textGray};font-style:normal;font-weight:400;}`;
const Progress=styled.div`display:flex;gap:3px;margin-bottom:16px;i{display:block;flex:1;height:2px;background:${({theme})=>theme.colors.border};}i.done{background:${({theme})=>theme.colors.primary};}`;
const Question=styled.p`font-size:13px;font-weight:600;line-height:20px;`;
const Sub=styled.p`margin-top:5px;color:${({theme})=>theme.colors.textGray};font-size:11px;line-height:18px;`;
const Option=styled.button`width:100%;margin-top:6px;padding:9px 11px;border:1px solid ${({theme})=>theme.colors.border};border-radius:8px;text-align:left;font-size:12px;`;
const Complete=styled.div`display:flex;align-items:center;gap:6px;padding:9px 11px;border-radius:7px;background:${({theme})=>theme.colors.primaryLight};color:${({theme})=>theme.colors.primary};font-size:12px;font-weight:600;img{width:11px;height:11px;}`;
const Label=styled.p`margin:15px 0 8px;color:${({theme})=>theme.colors.textGray};font-size:12px;`;
const Improve=styled(Option)`margin-top:5px;color:${({theme})=>theme.colors.textDark};font-size:13px;`;
const Composer=styled.div`position:absolute;left:0;right:0;bottom:0;padding:12px 14px;border-top:1px solid ${({theme})=>theme.colors.border};background:white;textarea{width:100%;height:59px;padding:10px 11px;resize:none;border:1px solid ${({theme})=>theme.colors.border};border-radius:8px;font:inherit;font-size:13px;&:focus{outline:none;border-color:${({theme})=>theme.colors.primary};}}`;
const ComposerActions=styled.div`display:flex;justify-content:space-between;margin-top:10px;button{height:28px;padding:0 10px;border:1px solid ${({theme})=>theme.colors.border};border-radius:6px;color:${({theme})=>theme.colors.textGray};font-size:11px;}button:last-child{border:0;background:${({theme})=>theme.colors.primary};color:white;&:disabled{background:${({theme})=>theme.colors.border};}}`;
const Picker=styled.div`position:absolute;z-index:2;left:16px;right:16px;top:175px;padding:14px;border:1px solid ${({theme})=>theme.colors.border};border-radius:12px;background:white;box-shadow:0 5px 18px rgba(0,0,0,.12);h3{font-size:13px;margin-bottom:8px;}label{display:flex;gap:8px;margin:10px 0;font-size:12px;line-height:18px;}button{width:100%;height:34px;margin-top:8px;border-radius:7px;background:${({theme})=>theme.colors.primary};color:white;font-size:12px;&:disabled{background:${({theme})=>theme.colors.border};color:${({theme})=>theme.colors.textGray};}}`;
const Suggestion=styled.div`padding:14px 16px;h3{font-size:13px;margin-bottom:14px;}b{display:block;margin:10px 0 6px;color:${({theme})=>theme.colors.textGray};font-size:11px;letter-spacing:.06em;}b.green{color:${({theme})=>theme.colors.primary};}.box{padding:10px 12px;border:1px solid ${({theme})=>theme.colors.border};border-radius:7px;color:${({theme})=>theme.colors.textGray};font-size:12px;line-height:20px}.box.new{border-color:${({theme})=>theme.colors.primary};background:${({theme})=>theme.colors.primaryLight};color:${({theme})=>theme.colors.textDark};}`;
const SuggestActions=styled.div`display:grid;grid-template-columns:1fr 1fr 1.4fr;gap:6px;margin-top:14px;button{height:34px;border:1px solid ${({theme})=>theme.colors.border};border-radius:7px;font-size:11px;}button:last-child{border:0;background:${({theme})=>theme.colors.primary};color:white;}`;
const ConfirmActions=styled.div`display:grid;grid-template-columns:1fr auto;gap:6px;margin-top:12px;button{height:34px;border-radius:7px;font-size:13px;font-weight:600;}button:first-child{background:${({theme})=>theme.colors.primary};color:white;}button:last-child{padding:0 12px;color:${({theme})=>theme.colors.textGray};}`;
const SuggestEdit=styled.textarea`width:100%;min-height:130px;padding:10px 12px;resize:none;border:1.5px solid ${({theme})=>theme.colors.primary};border-radius:7px;background:${({theme})=>theme.colors.primaryLight};color:${({theme})=>theme.colors.textDark};font:inherit;font-size:12px;line-height:20px;&:focus{outline:none;}`;

export default function AICoachPanel({ roleText, records = [], onApply, startStage = "questions" }){
 const proposal=roleText.replace("공동으로 결정했습니다.","공동으로 결정했지만, 사용자 데이터를 근거로 논의를 이끌고 합의를 만드는 역할을 맡았습니다.");
 const [stage,setStage]=useState(startStage),[step,setStep]=useState(1),[picker,setPicker]=useState(false),[selected,setSelected]=useState([]),[input,setInput]=useState(""),[editingSuggestion,setEditingSuggestion]=useState(false),[suggestion,setSuggestion]=useState(proposal);
 const choose=()=>setStep(2);
 const toggle=id=>setSelected(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]);
 if(stage==="suggestion")return <Panel><Header>AI로 경험 다듬기</Header><Suggestion><h3>나의 역할 수정 제안</h3><b>기존</b><div className="box">{roleText}</div><b className="green">제안</b>{editingSuggestion?<SuggestEdit autoFocus value={suggestion} onChange={e=>setSuggestion(e.target.value)}/>:<div className="box new">{suggestion}</div>}<SuggestActions><button onClick={()=>{setSuggestion(proposal);setEditingSuggestion(false);setStage("complete");}}>다시 요청</button><button onClick={()=>setEditingSuggestion(v=>!v)}>{editingSuggestion?"수정 완료":"직접 수정"}</button><button onClick={()=>{onApply(suggestion);setStage("complete");}}>반영하기</button></SuggestActions></Suggestion><Composer><textarea placeholder="나의 역할을 어떻게 다듬을까요?" value={input} onChange={e=>setInput(e.target.value)}/><ComposerActions><button onClick={()=>setPicker(true)}>＋ 30초 기록</button><button disabled={!input.trim()} onClick={()=>setStage("suggestion")}>전송</button></ComposerActions></Composer></Panel>;
 return <Panel><Header>AI로 경험 다듬기</Header><Body>{stage==="questions"?<><StepHead><span><img src={aiDocument} alt=""/>확인할 내용</span><em>{step} / 2</em></StepHead><Progress><i className="done"/><i className={step===2?"done":""}/></Progress><Question>{step===1?"사용자 인터뷰를 직접 설계하고 진행하셨나요?":"핵심 기능을 줄이는 결정에 직접 참여하셨나요?"}</Question><Sub>{step===1?"프로젝트에서 맡았던 역할을 확인해 주세요.":"의사 결정 과정에서 맡았던 역할을 확인해 주세요."}</Sub>{step===1?["직접 설계·진행했어요","일부 참여했어요","참여하지 않았어요"].map(x=><Option key={x} onClick={choose}>{x}</Option>):<ConfirmActions><button onClick={()=>setStage("complete")}>승인</button><button onClick={()=>setStage("complete")}>거절</button></ConfirmActions>}</>:<><Complete><img src={checkIcon} alt=""/>확인 완료됐어요.</Complete><Label>더 구체화하면 좋은 부분</Label>{["나의 역할","핵심 판단","결과와 변화"].map(x=><Improve key={x} onClick={()=>setStage("suggestion")}>{x}</Improve>)}</>}</Body><Composer><textarea placeholder="무엇을 다듬고 싶나요?" value={input} onChange={e=>setInput(e.target.value)}/><ComposerActions><button onClick={()=>setPicker(true)}>＋ 30초 기록</button><button disabled={!input.trim()} onClick={()=>setStage("suggestion")}>전송</button></ComposerActions></Composer>{picker&&<Picker><h3>기록 선택</h3>{records.length?records.map(r=><label key={r.id}><input type="checkbox" checked={selected.includes(r.id)} onChange={()=>toggle(r.id)}/><span>{r.content}</span></label>):<Sub>연결된 30초 기록이 없습니다.</Sub>}<button disabled={!selected.length} onClick={()=>{setPicker(false);setStage("suggestion");}}>선택한 기록 추가 ({selected.length})</button></Picker>}</Panel>;
}
